#!/bin/bash

PICDIR="/home/steve/Dropbox/Backgrounds"

FILE=`ls $PICDIR | sort -R | tail -1`
#echo "$# arguments present"
#echo "$1"
PID=$(pgrep gnome-session)
echo $PID
if [ -z "$PID" ]; then
	DISPLAY=:0 feh --bg-scale "$PICDIR/$FILE" &
else
	export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)
	gsettings set org.gnome.desktop.background picture-uri "file://$PICDIR/$FILE"
fi


